// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EntityNode = { chunk_id: string, chunk_order_index: number, doc_id: string, entity_description: string, entity_name: string, entity_type: string, };
