// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GraphSearchEntity = { id: string, entity_name: string, entity_description: string, entity_type: string, };
