// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GraphSearchEdge } from "./GraphSearchEdge";
import type { GraphSearchEntity } from "./GraphSearchEntity";

export type GraphSearchPath = { nodes: Array<GraphSearchEntity>, edges: Array<GraphSearchEdge>, };
