// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityResponse } from "./EntityResponse";
import type { RelationshipEdgeResponse } from "./RelationshipEdgeResponse";

export type GraphResponse = { entities: Array<EntityResponse>, relations: Array<RelationshipEdgeResponse>, };
