// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GraphSearchResult } from "./GraphSearchResult";

export type GraphSearchResponse = { query: string | null, results: Array<GraphSearchResult> | null, message: string | null, paths: Array<string> | null, };
