// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GraphSearchEdge = { relation_description: string, relationship_keywords: Array<string>, source_entity_id: string, target_entity_id: string, is_forward: boolean, };
