// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GraphSearchEntity } from "./GraphSearchEntity";
import type { GraphSearchPath } from "./GraphSearchPath";

export type GraphSearchResult = { symptom: GraphSearchEntity, paths: Array<GraphSearchPath>, };
