// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RelationshipEdgeResponse = { id: string, source_node_id: string, target_node_id: string, relation_description: string, };
